name: geo-env
channels:
    - conda-forge
dependencies:
    - bokeh
    - cartopy
    - datapane
    - flask>=2.0.0
    - flask-caching
    - gdal
    - geemap>=0.11.1
    - geopandas
    - imageio
    - ipyvtklink
    - jupyter_bokeh
    - keplergl
    - laspy
    - leafmap>=0.11.3
    - localtileserver>=0.10.0
    - osmnx
    - pip
    - pydeck
    - pyntcloud
    - python>=3.9
    - pyvista
    - requests
    - rio-cogeo
    - tifffile
    - xarray_leaflet
    # - pip:
    #     - git+https://github.com/opengeos/leafmap
    #     - git+https://github.com/opengeos/geemap
