site_name: leafmap

site_url: https://leafmap.org

repo_url: https://github.com/giswqs/leafmap

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

# extra_javascript:
#     - javascripts/embed-amd.js
#     - javascripts/require.min.js

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          execute_ignore: "workshops/*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-198454981-1
#     - auto

extra:
    analytics:
        provider: google
        property: UA-198454981-1

nav:
    - Home: index.md
    - Installation: installation.md
    - Get Started: get-started.md
    - Usage: notebooks/00_key_features.ipynb
    - Interactive Maps: maps.md
    - Streamlit App: https://gishub.org/leafmap-apps
    - Tutorials: tutorials.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - YouTube Channel: https://www.youtube.com/c/QiushengWu
    - Report Issues: https://github.com/giswqs/leafmap/issues
    - API Reference:
          - basemaps module: basemaps.md
          - colormaps module: colormaps.md
          - common module: common.md
          - foliumap module: foliumap.md
          - heremap module: heremap.md
          - kepler module: kepler.md
          - leafmap module: leafmap.md
          - legends module: legends.md
          - osm module: osm.md
          - pydeck module: deck.md
          - toolbar module: toolbar.md
    - Workshops:
          - workshops/foss4g_2021.ipynb
    - Notebooks:
          - notebooks/00_key_features.ipynb
          - notebooks/01_leafmap_intro.ipynb
          - notebooks/02_using_basemaps.ipynb
          - notebooks/03_cog_stac.ipynb
          - notebooks/04_cog_mosaic.ipynb
          - notebooks/05_load_raster.ipynb
          - notebooks/06_legend.ipynb
          - notebooks/07_colorbar.ipynb
          - notebooks/08_whitebox.ipynb
          - notebooks/09_csv_to_points.ipynb
          - notebooks/10_add_vector.ipynb
          - notebooks/11_linked_maps.ipynb
          - notebooks/12_split_map.ipynb
          - notebooks/13_geopandas.ipynb
          - notebooks/14_postgis.ipynb
          - notebooks/15_openstreetmap.ipynb
          - notebooks/16_heremap.ipynb
          - notebooks/17_vector_tile_layer.ipynb
          - notebooks/18_point_layer.ipynb
          - notebooks/19_map_to_html.ipynb
          - notebooks/20_planet_imagery.ipynb
          - notebooks/21_ts_inspector.ipynb
          - notebooks/22_time_slider.ipynb
          - notebooks/23_colormaps.ipynb
          - notebooks/24_heatmap.ipynb
          - notebooks/25_map_title.ipynb
          - notebooks/26_kepler_gl.ipynb
          - notebooks/27_basemap_gallery.ipynb
          - notebooks/28_publish_map.ipynb
          - notebooks/29_pydeck.ipynb
          - notebooks/30_census_data.ipynb
          - notebooks/31_search_basemaps.ipynb
