name: default-environment
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - bokeh
  - cartopy
  - geopandas
  - h5netcdf
  - h5py
  - imageio
  - ipyvtklink
  - jupyter_bokeh
  - keplergl
  - laspy
  - opera-utils
  - osmnx
  - pyntcloud
  - pyvista
  - requests
  - rioxarray
  - rio-cogeo
  - xarray_leaflet
  - leafmap>=0.57
