name: default-environment
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - bokeh
  - cartopy
  # - datapane
  - flask>=2.0.0
  - flask-caching
  # - gdal
  # - geemap>=0.11.1 # Not possible due to ffmpeg dep
  - geopandas
  - h5netcdf
  - h5py
  - imageio
  - ipyvtklink
  - jupyter_bokeh
  - keplergl
  - laspy
  # - localtileserver>=0.10.0
  - opera-utils
  - osmnx
  - pip
  # Conflicting ipywidgets requirement pydeck requires <8
  # - pydeck
  - pyntcloud
  - python>=3.9
  - pyvista
  - requests
  - rioxarray
  - rio-cogeo
  # - tifffile
  - xarray_leaflet
  - pip:
    - leafmap>=0.11.3
